### ISSUE TITLE
More flexible data source model

### ISSUE THREAD

**Issue by ysangkok** [mit-dci/dlcoracle#4]
I want to use DLC for soccer, but it is inconvenient to encode the results of a football game into a uint64. It would be more usable if the data source worked with sets as its primary abstraction.

**Comment by gertjaap** [comment]
Hi @ysangkok,

Theoretically you can sign any message of 32 bytes using the signature scheme. I would recommend you take a look at our library for oracles over [here](https://github.com/mit-dci/dlc-oracle-go). 

The challenge is that the execution of contracts, that's part of [lit](https://github.com/mit-dci/lit) is currently centred around numerical messages. You can control lit using the RPC client [here](https://github.com/mit-dci/lit-rpc-client-go), there's examples [here](https://github.com/mit-dci/lit-rpc-client-go-samples). 

If you could further elaborate on your usecase maybe i can think of the necessary adjustments in lit to facilitate it. I was already looking into how we can give more control on the payouts of the contract from RPC.

**Comment by ysangkok** [comment]
All right, thanks for the response. I'll close this since it isn't a problem with the actual code.
